### ISSUE TITLE
movies container missing php dependencies

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/helioviewer.org-docker#36]
```
2024-05-01 10:11:10 PHP Fatal error:  Uncaught Error: Class "IMagick" not found in /var/www/api.helioviewer.org/src/Image/SubFieldImage.php:87
2024-05-01 10:11:10 Stack trace:
2024-05-01 10:11:10 #0 /var/www/api.helioviewer.org/src/Image/HelioviewerImage.php(69): Image_SubFieldImage->__construct()
2024-05-01 10:11:10 #1 /var/www/api.helioviewer.org/src/Image/ImageType/AIAImage.php(52): Image_HelioviewerImage->__construct()
2024-05-01 10:11:10 #2 /var/www/api.helioviewer.org/src/Image/Composite/HelioviewerCompositeImage.php(302): Image_ImageType_AIAImage->__construct()
2024-05-01 10:11:10 #3 /var/www/api.helioviewer.org/src/Image/Composite/HelioviewerCompositeImage.php(185): Image_Composite_HelioviewerCompositeImage->_buildImageLayer()
2024-05-01 10:11:10 #4 /var/www/api.helioviewer.org/src/Image/Composite/HelioviewerCompositeImage.php(1542): Image_Composite_HelioviewerCompositeImage->_buildCompositeImageLayers()
2024-05-01 10:11:10 #5 /var/www/api.helioviewer.org/src/Image/Composite/HelioviewerMovieFrame.php(28): Image_Composite_HelioviewerCompositeImage->build()
2024-05-01 10:11:10 #6 /var/www/api.helioviewer.org/src/Movie/HelioviewerMovie.php(446): Image_Composite_HelioviewerMovieFrame->__construct()
2024-05-01 10:11:10 #7 /var/www/api.helioviewer.org/src/Movie/HelioviewerMovie.php(218): Movie_HelioviewerMovie->_buildMovieFrames()
2024-05-01 10:11:10 #8 /var/www/api.helioviewer.org/src/Job/MovieBuilder.php(41): Movie_HelioviewerMovie->build()
2024-05-01 10:11:10 #9 /var/www/api.helioviewer.org/lib/Resque/Job.php(182): Job_MovieBuilder->perform()
2024-05-01 10:11:10 #10 /var/www/api.helioviewer.org/lib/Resque/Worker.php(237): Resque_Job->perform()
2024-05-01 10:11:10 #11 /var/www/api.helioviewer.org/lib/Resque/Worker.php(199): Resque_Worker->perform()
2024-05-01 10:11:10 #12 /var/www/api.helioviewer.org/scripts/resque.php(59): Resque_Worker->work()
2024-05-01 10:11:10 #13 {main}
2024-05-01 10:11:10   thrown in /var/www/api.helioviewer.org/src/Image/SubFieldImage.php on line 87
```

```
2024-05-01 10:13:52 PHP Fatal error:  Uncaught Error: Class "Redis" not found in /var/www/api.helioviewer.org/src/Helper/RedisCache.php:17
2024-05-01 10:13:52 Stack trace:
2024-05-01 10:13:52 #0 /var/www/api.helioviewer.org/src/Database/Statistics.php(115): RedisCache->__construct()
2024-05-01 10:13:52 #1 /var/www/api.helioviewer.org/src/Database/Statistics.php(140): Database_Statistics->_GetDevice()
2024-05-01 10:13:52 #2 /var/www/api.helioviewer.org/src/Movie/HelioviewerMovie.php(251): Database_Statistics->log()
2024-05-01 10:13:52 #3 /var/www/api.helioviewer.org/src/Job/MovieBuilder.php(41): Movie_HelioviewerMovie->build()
2024-05-01 10:13:52 #4 /var/www/api.helioviewer.org/lib/Resque/Job.php(182): Job_MovieBuilder->perform()
2024-05-01 10:13:52 #5 /var/www/api.helioviewer.org/lib/Resque/Worker.php(237): Resque_Job->perform()
2024-05-01 10:13:52 #6 /var/www/api.helioviewer.org/lib/Resque/Worker.php(199): Resque_Worker->perform()
2024-05-01 10:13:52 #7 /var/www/api.helioviewer.org/scripts/resque.php(59): Resque_Worker->work()
2024-05-01 10:13:52 #8 {main}
2024-05-01 10:13:52   thrown in /var/www/api.helioviewer.org/src/Helper/RedisCache.php on line 17
```

Need to install imagick and redis php packages in container build

**Comment by dgarciabriseno** [comment]
Fixed by #40
